### ISSUE TITLE
Fix `lowdb/sqlite.insertID` not adding generated ID to the row that is inserted

### ISSUE THREAD

**Issue by PhilippMDoerner** [PhilippMDoerner/lowdb#9]
Minimal example:

```nim
import lowdb/sqlite
import std/unittest

let dbConn = open(":memory:", "", "", "")
dbConn.exec sql"CREATE TABLE t1 (id SERIAL PRIMARY KEY, value TEXT)"

let id = dbConn.insertID sql"INSERT INTO t1(value) VALUES ('a')"
let rows: seq[Row] = dbConn.getAllRows(sql "SELECT * FROM t1")

assert rows.len == 1

let expectedValue: seq[Row] = @[
  @[
    DbValue(kind: dvkInt, i: id),
    DbValue(kind: dvkString, s: "a")
  ]
]
check rows == expectedValue
```

expectation: This should succeed.
`insertID` should insert an entry into the table AND add an auto-generated ID.

Currently it does not do that, it only adds the entry, it doesn't set the generated id.

**SideInformation**:

What's mysterious about this is, that it appears to generally work for norm, which is using lowdb and makes extensive use of it.
It also occurs in both nim 1.6.10 and 1.9.1, so it's not a bug caused by devel.

**Comment by ire4ever1190** [comment]
If you replace `SERIAL` with `INTEGER` it works (since `SERIAL` [is not a SQLite data type](https://stackoverflow.com/questions/19726028/sqlite3-serial-type-wasnt-incremented))

Reason it is returning a value is because it's returning the value of the hidden `ROWID` column. Replacing the `*` in the `SELECT` with `ROWID, value` also fixes this

**Comment by PhilippMDoerner** [comment]
Was a silliness in the tests then. Fixed it accordingly. Thanks for the research!
